
document.body.innerHTML += [
	  '<div id="wrapper">'
	, '<div id="chatroom">'
	, '<div id="toolbar">'
	, '<h4>Room Title</h4>'
	, '<span id="minimize" class="toolbar_btn">_</span>'
	, '<span id="close" class="toolbar_btn">X</span>'
	, '</div>'
	, '<div id="conversation">'
	, '<ul id="comment_list">'
	, '<li class="comment">'
  	, '<span class="name" title="Ke Wu"></span>'
  	, '<span class="content">hello world!  Welcome to Newspeak!</span>'
	, '</li>'
	, '</ul>'
	, '</div>'
	, '<div id="input">'
	, '<div id="promt">&gt;</div>'
	, '<textarea id="text_input" rows="1"></textarea>'
	, '</div>'
	, '</div>'
	, '</div>'
].join("");
