
document.body.innerHTML += [
	  '<div id="nsp_wrapper" style="z-index:1000000001;">'
	, '<div id="nsp_chatroom">'
	, '<div id="nsp_toolbar">'
	, '<h4 id="nsp_title">Room Title</h4>'
	, '<span id="nsp_minimize" class="nsp_toolbar_btn">_</span>'
	, '<span id="nsp_close" class="nsp_toolbar_btn">X</span>'
	, '</div>'
	, '<div id="nsp_conversation">'
	, '<ul id="nsp_comment_list">'
	, '<li class="nsp_comment">'
  	, '<span class="nsp_name" title="Ke Wu"></span>'
  	, '<span class="nsp_content">hello world!  Welcome to Newspeak!</span>'
	, '</li>'
	, '</ul>'
	, '</div>'
	, '<div id="nsp_input">'
	, '<div id="nsp_promt">&gt;</div>'
	, '<textarea id="nsp_text_input" rows="1" style="margin:0;padding:0;"></textarea>'
	, '</div>'
	, '</div>'
	, '</div>'
].join("");
